### ISSUE TITLE
Aternos server?

### ISSUE THREAD

**Issue by electricsteve** [ExcessiveAmountsOfZombies/OctoEconomyApi#1]
(If there is a mod of this on curseforge/modrint or something pls say it)
So, on Aternos you can't upload mods yourself and you must suggest it from a supported website. Now is there none of this mod on a supported website. Do the mods shoppy and EightsEconomyP work without this mod, or is there an other way to do this?

**Comment by ExcessiveAmountsOfZombies** [comment]
This mod is bundled with EgihtsEconomyP and Shoppy

**Comment by electricsteve** [comment]
ok
